# Generated by Django 3.0.6 on 2020-12-29 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201228_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 1, 20, 54, 785187), null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 1, 20, 54, 790487), null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 1, 20, 54, 789209), null=True),
        ),
    ]
